#!/usr/bin/env bash

####################################################################
# bl - BLACKLIST CHECK UNIX/LINUX UTILITY                          #
# copyright: (c) 2014 Anders Aarvik                                #
# author: Anders Aarvik (aarvik92@gmail.com) and contributors      #
# license: MIT licensed. See LICENSE                               #
# description: I was just a bit tired of web interfaces            #
####################################################################
# revisado por moucho                                              #
####################################################################

# colorear #
colorear(){
  LGREEN="\033[1;32m"
  LRED="\033[1;31m"
  YELLOW="\033[1;33m"
  NORMAL="\033[m"
 
  color=\$${1:-NORMAL}
 
  echo -ne "$(eval echo ${color})"
  cat
 
  echo -ne "${NORMAL}"
}

# Revisíon inicial #
if  [ -z "$1" ] || [ ! -z  "$2" ];then
  echo -e "\\nEl único argumento debe ser un dominio FQDN o una IP.\\n" | colorear LRED
  exit 1
fi

# main #
main() {
  fqdn=$(echo "$1" | grep -P "(?=^.{5,254}$)(^(?:(?!\d+\.)[a-za-z0-9_\-]{1,63}\.?)+(?:[a-za-z]{2,})$)")
  if [[ $fqdn ]] ; then
    echo -e "\\nEl dominio que se revisará: $1" | colorear LGREEN
    domain=$(host "$1" | head -n1 | awk '{print $4}')
    reverseit "$domain"
    if [ $? != 0 ]; then
      echo -e "\\nEl dominio no resuelve o su IP no es válida.\\n" | colorear LRED
      exit 2
    fi
  else
    echo -e "\\nLa IP que se revisará: $1" | colorear LGREEN
    reverseit "$1"
    if [ $? != 0 ]; then
      echo -e "\\nNo es una IP válida.\\n" | colorear LRED
      exit 2
    fi
  fi

  loopthroughblacklists "$1"
  senderscore
}

#### reverseit ####
reverseit() {
  reverse=$(echo "$1" |  sed -ne "s~^\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)$~\4.\3.\2.\1~p")
  if [ "x${reverse}" = "x" ] ; then
    return 5
  fi
}

#### loopthroughblacklists ####
loopthroughblacklists() {
  reverse_dns=$(dig +short -x "$1")
  echo -e "$1 resuelve a ${reverse_dns:----}\\n" | colorear YELLOW
  echo

  for bl in ${blacklists} ; do

      printf $(env tz=Europe/Madrid date "+%y-%m-%d_%h:%m:%s_%z")
      printf "%-40s" " ${reverse}.${bl}."

      listed="$(dig +short -t a ${reverse}.${bl}.)"

      if [[ $listed ]]; then

        if [[ $listed == *"timed out"* ]]; then

          echo "[tiempo de espera agotado]" | colorear YELLOW 
        else
        
          echo "[Listada] (${listed})" | colorear LRED
        fi
      else

          echo "[No listada]" | colorear LGREEN
      fi
  done
}

#### senderscore #### 

senderscore() {
  reputacion=$(dig +short "${reverse}.score.senderscore.com"|cut -d'.' -f4)
  if [ ! -z "$reputacion" ]; then
    if [[ "$reputacion" -ge 50 ]]; then
      colorrespuesta=LGREEN
    else
      colorrespuesta=LRED
    fi
    echo -e "\\nLa IP tiene una reputación en Sender Score de ${reputacion} sobre 100.\\n" | colorear $colorrespuesta
  else
    echo -e "\\nLa IP no ha enviado correos suficientes para estar clasificada en Sender Score.\\n" | colorear YELLOW
  fi
}

#### blacklists - grabbed from http://multirbl.valli.org/ ####
blacklists="
  0spamurl.fusionzero.com
  uribl.zeustracker.abuse.ch
  uribl.abuse.ro
  l1.apews.org
  dnsbl.aspnet.hu
  bsb.empty.us
  bsb.spamlookup.net
  ex.dnsbl.org
  in.dnsbl.org
  dnsbl.othello.ch
  (hidden)
  ubl.nszones.com
  uribl.pofon.foobar.hu
  dyndns.rbl.jp
  url.rbl.jp
  abuse.rfc-clueless.org
  bogusmx.rfc-clueless.org
  dsn.rfc-clueless.org
  elitist.rfc-clueless.org
  fulldom.rfc-clueless.org
  postmaster.rfc-clueless.org
  whois.rfc-clueless.org
  rhsbl.rymsho.ru
  rhsbl.scientificspam.net
  nomail.rhsbl.sorbs.net
  badconf.rhsbl.sorbs.net
  rhsbl.sorbs.net
  fresh.spameatingmonkey.net
  fresh10.spameatingmonkey.net
  fresh15.spameatingmonkey.net
  uribl.spameatingmonkey.net
  urired.spameatingmonkey.net
  dbl.spamhaus.org
  multi.surbl.org
  uribl.swinog.ch
  dob.sibl.support-intelligence.net
  black.uribl.com
  grey.uribl.com
  multi.uribl.com
  red.uribl.com
  uri.blacklist.woody.ch
  rhsbl.zapbl.net
  hostkarma.junkemailfilter.com
  reputation-domain.rbl.scrolloutf1.com
  reputation-ns.rbl.scrolloutf1.com
  nobl.junkemailfilter.com
  iddb.isipp.com
  _vouch.dwl.spamhaus.org
  white.uribl.com
  list.anonwhois.net
"

### iniciar script ###
main "$1"
