#!/usr/bin/env bash

####################################################################
# bl - BLACKLIST CHECK UNIX/LINUX UTILITY                          #
# copyright: (c) 2014 Anders Aarvik                                #
# author: Anders Aarvik (aarvik92@gmail.com) and contributors      #
# license: MIT licensed. See LICENSE                               #
# description: I was just a bit tired of web interfaces            #
####################################################################
# revisado por moucho                                              #
####################################################################

# colorear #
colorear(){
  LGREEN="\033[1;32m"
  LRED="\033[1;31m"
  YELLOW="\033[1;33m"
  NORMAL="\033[m"
 
  color=\$${1:-NORMAL}
 
  echo -ne "$(eval echo ${color})"
  cat
 
  echo -ne "${NORMAL}"
}

# Revisíon inicial #
if  [ -z "$1" ] || [ ! -z  "$2" ];then
  echo -e "\\nEl único argumento debe ser un dominio FQDN o una IP.\\n" | colorear LRED
  exit 1
fi

# main #
main() {
  fqdn=$(echo "$1" | grep -P "(?=^.{5,254}$)(^(?:(?!\d+\.)[a-za-z0-9_\-]{1,63}\.?)+(?:[a-za-z]{2,})$)")
  if [[ $fqdn ]] ; then
    echo -e "\\nEl dominio que se revisará: $1" | colorear LGREEN
    domain=$(host "$1" | head -n1 | awk '{print $4}')
    reverseit "$domain"
    if [ $? != 0 ]; then
      echo -e "\\nEl dominio no resuelve o su IP no es válida.\\n" | colorear LRED
      exit 2
    fi
  else
    echo -e "\\nLa IP que se revisará: $1" | colorear LGREEN
    reverseit "$1"
    if [ $? != 0 ]; then
      echo -e "\\nNo es una IP válida.\\n" | colorear LRED
      exit 2
    fi
  fi

  loopthroughblacklists "$1"
  senderscore
}

#### reverseit ####
reverseit() {
  reverse=$(echo "$1" |  sed -ne "s~^\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)$~\4.\3.\2.\1~p")
  if [ "x${reverse}" = "x" ] ; then
    return 5
  fi
}

#### loopthroughblacklists ####
loopthroughblacklists() {
  reverse_dns=$(dig +short -x "$1")
  echo -e "$1 resuelve a ${reverse_dns:----}\\n\\n" | colorear YELLOW

  for bl in ${blacklists} ; do

      printf $(env tz=Europe/Madrid date "+%y-%m-%d_%h:%m:%s_%z")
      printf "%-56s" " ${reverse}.${bl}."

      listed="$(dig +short -t a ${reverse}.${bl}.)"

      if [[ $listed ]]; then

        if [[ $listed == *"timed out"* ]]; then

          echo "[tiempo de espera agotado]" | colorear YELLOW 
        else
        
          echo "[Listada] (${listed})" | colorear LRED
        fi
      else

          echo "[No listada]" | colorear LGREEN
      fi
  done
}

#### senderscore #### 

senderscore() {
  reputacion=$(dig +short "${reverse}.score.senderscore.com"|cut -d'.' -f4)
  if [ ! -z "$reputacion" ]; then
    if [[ "$reputacion" -ge 50 ]]; then
      colorrespuesta=LGREEN
    else
      colorrespuesta=LRED
    fi
    echo -e "\\n\\nLa IP tiene una reputación en Sender Score de ${reputacion} sobre 100.\\n" | colorear $colorrespuesta
  else
    echo -e "\\n\\nLa IP no ha enviado correos suficientes para estar clasificada en Sender Score.\\n" | colorear YELLOW
  fi
}

#### blacklists - grabbed from http://multirbl.valli.org/ ####
blacklists="
  0spam.fusionzero.com
  0spamtrust.fusionzero.com
  0spam-killlist.fusionzero.com
  0spamurl.fusionzero.com
  uribl.zeustracker.abuse.ch
  ipbl.zeustracker.abuse.ch
  contacts.abuse.net
  rbl.abuse.ro
  uribl.abuse.ro
  abuse-contacts.abusix.org
  spam.dnsbl.anonmails.de
  dnsbl.anticaptcha.net
  dnsbl6.anticaptcha.net
  orvedb.aupads.org
  rsbl.aupads.org
  block.ascams.com
  superblock.ascams.com
  aspews.ext.sorbs.net
  ips.backscatterer.org
  b.barracudacentral.org
  bb.barracudacentral.org
  list.bbfh.org
  l1.bbfh.ext.sorbs.net
  l2.bbfh.ext.sorbs.net
  l3.bbfh.ext.sorbs.net
  l4.bbfh.ext.sorbs.net
  all.ascc.dnsbl.bit.nl
  all.v6.ascc.dnsbl.bit.nl
  all.dnsbl.bit.nl
  ipv6.all.dnsbl.bit.nl
  bitonly.dnsbl.bit.nl
  blackholes.tepucom.nl
  blacklist.netcore.co.in
  rbl.blakjak.net
  netscan.rbl.blockedservers.com
  rbl.blockedservers.com
  spam.rbl.blockedservers.com
  list.blogspambl.com
  bsb.empty.us
  bsb.spamlookup.net
  query.bondedsender.org
  plus.bondedsender.org
  dnsbl1.dnsbl.borderware.com
  dnsbl2.dnsbl.borderware.com
  dnsbl3.dnsbl.borderware.com
  dul.dnsbl.borderware.com
  blacklist.sci.kun.nl
  whitelist.sci.kun.nl
  dul.blackhole.cantv.net
  hog.blackhole.cantv.net
  rhsbl.blackhole.cantv.net
  rot.blackhole.cantv.net
  spam.blackhole.cantv.net
  cbl.anti-spam.org.cn
  cblplus.anti-spam.org.cn
  cblless.anti-spam.org.cn
  cdl.anti-spam.org.cn
  cml.anti-spam.org.cn
  cbl.abuseat.org
  rbl.choon.net
  rwl.choon.net
  ipv6.rbl.choon.net
  ipv6.rwl.choon.net
  zz.countries.nerd.dk
  dnsbl.cyberlogic.net
  bogons.cymru.com
  v4.fullbogons.cymru.com
  v6.fullbogons.cymru.com
  origin.asn.cymru.com
  origin6.asn.cymru.com
  peer.asn.cymru.com
  tor.dan.me.uk
  torexit.dan.me.uk
  dnsbl.darklist.de
  ex.dnsbl.org
  in.dnsbl.org
  rbl.dns-servicios.com
  dnsbl.abyan.es
  dnsbl.beetjevreemd.nl
  dnsbl.calivent.com.pe
  dnsbl.isx.fr
  dnsbl.mcu.edu.tw
  dnsbl.net.ua
  dnsbl.rv-soft.info
  dnsblchile.org
  dnsrbl.org
  dwl.dnswl.org
  list.dnswl.org
  vote.drbl.caravan.ru
  work.drbl.caravan.ru
  vote.drbldf.dsbl.ru
  work.drbldf.dsbl.ru
  vote.drbl.gremlin.ru
  work.drbl.gremlin.ru
  bl.drmx.org
  dnsbl.dronebl.org
  rbl.efnet.org
  rbl.efnetrbl.org
  tor.efnet.org
  bl.emailbasura.org
  rbl.fasthosts.co.uk
  bl.fmb.la
  communicado.fmb.la
  nsbl.fmb.la
  sa.fmb.la
  short.fmb.la
  fnrbl.fast.net
  forbidden.icm.edu.pl
  88.blocklist.zap
  hil.habeas.com
  accredit.habeas.com
  sa-accredit.habeas.com
  hul.habeas.com
  sohul.habeas.com
  hostkarma.junkemailfilter.com
  black.junkemailfilter.com
  nobl.junkemailfilter.com
  dnsbl.cobion.com
  spamrbl.imp.ch
  wormrbl.imp.ch
  dnsbl.inps.de
  dnswl.inps.de
  rbl.interserver.net
  (hidden)
  (hidden)
  (hidden)
  rbl.iprange.net
  iadb.isipp.com
  iadb2.isipp.com
  iddb.isipp.com
  wadb.isipp.com
  whitelist.rbl.ispa.at
  mail-abuse.blacklist.jippg.org
  dnsbl.justspam.org
  dnsbl.kempt.net
  spamlist.or.kr
  bl.konstant.no
  admin.bl.kundenserver.de
  relays.bl.kundenserver.de
  schizo-bl.kundenserver.de
  spamblock.kundenserver.de
  worms-bl.kundenserver.de
  spamguard.leadmon.net
  rbl.lugh.ch
  dnsbl.madavi.de
  niprbl.mailcleaner.net
  uribl.mailcleaner.net
  blacklist.mailrelay.att.net
  bl.mailspike.net
  rep.mailspike.net
  wl.mailspike.net
  z.mailspike.net
  bl.mav.com.br
  cidr.bl.mcafee.com
  rbl.megarbl.net
  dnsbl.forefront.microsoft.com
  bl.mipspace.com
  combined.rbl.msrbl.net
  images.rbl.msrbl.net
  phishing.rbl.msrbl.net
  spam.rbl.msrbl.net
  virus.rbl.msrbl.net
  web.rbl.msrbl.net
  (hidden)
  relays.nether.net
  trusted.nether.net
  unsure.nether.net
  ix.dnsbl.manitu.net
  no-more-funn.moensted.dk
  (hidden)
  wl.nszones.com
  dyn.nszones.com
  sbl.nszones.com
  bl.nszones.com
  ubl.nszones.com
  dnsbl.openresolvers.org
  blacklist.mail.ops.asp.att.net
  blacklist.sequoia.ops.asp.att.net
  spam.pedantic.org
  pofon.foobar.hu
  ispmx.pofon.foobar.hu
  uribl.pofon.foobar.hu
  (hidden)
  (hidden)
  safe.dnsbl.prs.proofpoint.com
  bad.psky.me
  psbl.surriel.com
  whitelist.surriel.com
  all.rbl.jp
  dyndns.rbl.jp
  short.rbl.jp
  url.rbl.jp
  virus.rbl.jp
  rbl.rbldns.ru
  rbl.schulte.org
  rbl.zenon.net
  rbl.realtimeblacklist.com
  access.redhawk.org
  eswlrev.dnsbl.rediris.es
  mtawlrev.dnsbl.rediris.es
  abuse.rfc-clueless.org
  bogusmx.rfc-clueless.org
  dsn.rfc-clueless.org
  elitist.rfc-clueless.org
  fulldom.rfc-clueless.org
  postmaster.rfc-clueless.org
  whois.rfc-clueless.org
  dnsbl.rizon.net
  mailsl.dnsbl.rjek.com
  urlsl.dnsbl.rjek.com
  dynip.rothen.com
  asn.routeviews.org
  aspath.routeviews.org
  dnsbl.rymsho.ru
  rhsbl.rymsho.ru
  all.s5h.net
  public.sarbl.org
  rhsbl.scientificspam.net
  bl.scientificspam.net
  reputation-domain.rbl.scrolloutf1.com
  reputation-ip.rbl.scrolloutf1.com
  reputation-ns.rbl.scrolloutf1.com
  tor.dnsbl.sectoor.de
  exitnodes.tor.dnsbl.sectoor.de
  query.senderbase.org
  sa.senderbase.org
  rf.senderbase.org
  bl.score.senderscore.com
  score.senderscore.com
  singular.ttk.pte.hu
  blackholes.scconsult.com
  dnsbl.sorbs.net
  problems.dnsbl.sorbs.net
  proxies.dnsbl.sorbs.net
  relays.dnsbl.sorbs.net
  safe.dnsbl.sorbs.net
  nomail.rhsbl.sorbs.net
  badconf.rhsbl.sorbs.net
  dul.dnsbl.sorbs.net
  zombie.dnsbl.sorbs.net
  block.dnsbl.sorbs.net
  escalations.dnsbl.sorbs.net
  http.dnsbl.sorbs.net
  misc.dnsbl.sorbs.net
  smtp.dnsbl.sorbs.net
  socks.dnsbl.sorbs.net
  rhsbl.sorbs.net
  spam.dnsbl.sorbs.net
  recent.spam.dnsbl.sorbs.net
  new.spam.dnsbl.sorbs.net
  old.spam.dnsbl.sorbs.net
  web.dnsbl.sorbs.net
  korea.services.net
  geobl.spameatingmonkey.net
  origin.asn.spameatingmonkey.net
  backscatter.spameatingmonkey.net
  badnets.spameatingmonkey.net
  bl.spameatingmonkey.net
  fresh.spameatingmonkey.net
  fresh10.spameatingmonkey.net
  fresh15.spameatingmonkey.net
  bl.ipv6.spameatingmonkey.net
  netbl.spameatingmonkey.net
  uribl.spameatingmonkey.net
  urired.spameatingmonkey.net
  netblockbl.spamgrouper.to
  all.spam-rbl.fr
  bl.spamcop.net
  sbl.spamdown.org
  dbl.spamhaus.org
  _vouch.dwl.spamhaus.org
  pbl.spamhaus.org
  sbl.spamhaus.org
  sbl-xbl.spamhaus.org
  swl.spamhaus.org
  xbl.spamhaus.org
  zen.spamhaus.org
  feb.spamlab.com
  rbl.spamlab.com
  all.spamrats.com
  dyna.spamrats.com
  noptr.spamrats.com
  spam.spamrats.com
  spamsources.fabel.dk
  dnsbl.spfbl.net
  dnswl.spfbl.net
  dul.pacifier.net
  bl.suomispam.net
  dbl.suomispam.net
  gl.suomispam.net
  multi.surbl.org
  srn.surgate.net
  dnsrbl.swinog.ch
  uribl.swinog.ch
  rbl.tdk.net
  st.technovision.dk
  dob.sibl.support-intelligence.net
  dbl.tiopan.com
  bl.tiopan.com
  dnsbl.tornevall.org
  r.mail-abuse.com
  q.mail-abuse.com
  rbl2.triumf.ca
  wbl.triumf.ca
  truncate.gbudb.net
  dunk.dnsbl.tuxad.de
  hartkore.dnsbl.tuxad.de
  dnsbl-0.uceprotect.net
  dnsbl-1.uceprotect.net
  dnsbl-2.uceprotect.net
  dnsbl-3.uceprotect.net
  ubl.unsubscore.com
  black.uribl.com
  grey.uribl.com
  multi.uribl.com
  red.uribl.com
  white.uribl.com
  free.v4bl.org
  ip.v4bl.org
  all.rbl.webiron.net
  babl.rbl.webiron.net
  cabl.rbl.webiron.net
  crawler.rbl.webiron.net
  stabl.rbl.webiron.net
  ips.whitelisted.org
  blacklist.woody.ch
  ipv6.blacklist.woody.ch
  uri.blacklist.woody.ch
  db.wpbl.info
  bl.blocklist.de
  dnsbl.zapbl.net
  rhsbl.zapbl.net
"

### iniciar script ###
main "$1"
